name: Auto mycaret
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pycaret[full]
      - name: Run app.py
        run: |
          python app.py  # generate plot.png

          # Create CML report
          cat metrics.txt >> report.md
          # echo '![](./plot.png "Confusion Matrix")' >> report.md
          # cml comment create report.md
      - name: Finalising
        run: |
          echo "Done!"